### ISSUE TITLE
Checking for LAN hardware _after_ getting an IP via DHCP is pretty pointless.

### ISSUE THREAD

**Issue by felmue** [m5stack/M5Module-LAN-13.2#1]
### Describe the bug

Hello guys

the `HTTP.ino`, `MQTT.ino` and `WebServer.ino` examples all first try in a while loop to get an IP address via DHCP. And only **after** successfully getting an IP address the code continues to check for the presence of the LAN hardware. This is pretty pointless in my opinion since getting an IP address only can succeed if the LAN hardware is present in the first place.

I suggest to either remove the LAN hardware is present code completely or test for it **before** trying to get an IP address. For that to work you'll need to call `W5100.init();` first though.

Thanks
Felix

### To reproduce

n/a

### Expected behavior

n/a

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Additional context

This is not a bug per se. It's more of an optimization. 

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5Stack/issues?q=)
- [X] My report contains all necessary details

**Comment by Gitshaoxiang** [comment]
yeah, thanks for the feedback.  we will update the example later.
